version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"    
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGSQL_SOCKET_DIR: /var/run/postgresql/.s.PGSQL.5432
    ports:
      - "65432:5432"
