# version: "3"

# services: 
#   app:
#     build: .
#     command: bundle exec rails s -p 3000 -b "0.0.0.0"    
#     volumes:
#       - .:/rails_docker_app
#       - bundle:/usr/local/bundle
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     stdin_open: true
#     tty: true
#     environment:
#       RAILS_ENV: development
#       DB_USERNAME: nguyenminhhuy89
#       DB_PASSWORD: 'Hanhnguyen123'
#       DB_HOST: blgdb
#   db:
#     environment:
#       POSTGRES_HOST_AUTH_METHOD: trust
#     image: postgresql:14.9
#     ports:
#       - "15432:5432"
#     networks:
#       - postgres
# networks:
#   postgres:
#     driver: bridge

# volumes:
#   db_data:
#     driver: local
#   bundle:
#     driver: local

version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"    
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGSQL_SOCKET_DIR: /var/run/postgresql/.s.PGSQL.5432
      DB_USERNAME: nguyenminhhuy89
      DB_PASSWORD: 'Hanhnguyen123'
