version: 2.1

orbs:
  ruby: circleci/ruby@1.1

jobs:
  build:  
    docker:
      - image: cimg/ruby:2.7.8
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
          BROWSERSTACK_USERNAME: "neonguyen_ZFe6Rb"
          BROWSERSTACK_ACCESS_KEY: "jNPzVHmLttrJY7mP6P8d"
          BROWSERSTACK_LOCAL: false
          BROWSERSTACK_LOCAL_IDENTIFIER: "neonguyen"
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: blog
    resource_class: large
    working_directory: ~/app

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: install apt
          command: sudo apt-get update -qq && sudo apt-get install --no-install-recommends -y curl postgresql postgresql-contrib libvips42 nodejs gconf-service libasound2 libgconf-2-4 libgcrypt20 fonts-liberation libatk-bridge2.0-0 libatspi2.0-0 libgbm1 libgtk-3-0 libu2f-udev xdg-utils
      - run:
          name: install chrome-webdriver
          command: sudo apt update && curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/chrome.deb && sudo apt install -y /tmp/chrome.deb && sudo apt update && sudo apt install -y chromium-browser
      - run:
          name: Database setup
          command: bundle exec rails db:create db:migrate RAILS_ENV=test
          environment:
            RAILS_ENV: test
      - run:
          name: Run rspec
          command: bundle exec rspec
      # - run:
      #     name: Run parallel
      #     command: ruby spec/parallel.rb

workflows:
  test:
    jobs:
      - build