version: 2.1

orbs:
  ruby: circleci/ruby@1.1

jobs:
  build:  
    docker:
      - image: cimg/ruby:2.7.8
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: blog
    resource_class: large
    working_directory: ~/app

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: install apt
          command: sudo apt-get update -qq && sudo apt-get install --no-install-recommends -y curl postgresql postgresql-contrib libvips nodejs gconf-service libasound2 libgconf-2-4 libgcrypt11 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk2.0-0 libnspr4 libnss3 libstdc++6 libx11-6
      - run:
          name: install chrome-webdriver
          command: sudo apt update && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo dpkg -i google-chrome*.deb && rm google-chrome*.deb && wget -N https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && chmod +x chromedriver && cp chromedriver /usr/local/bin && rm chromedriver_linux64.zip && rm chromedriver
      - run:
          name: Database setup
          command: bundle exec rails db:create db:migrate RAILS_ENV=test
          environment:
            RAILS_ENV: test
      - run:
          name: Run rspec
          command: bundle exec rspec

workflows:
  test:
    jobs:
      - build