---
- !ruby/object:Product
  id: 1
  name: Book
  producttype: !ruby/object:ProductType
    id: 1
    name: Book
    typetax: !ruby/object:TypeTax
      id: 1
      name: Exempt
      tax: 0
- !ruby/object:Product
  id: 2
  name: Music Cd
  producttype: !ruby/object:ProductType
    id: 2
    name: Normal Good
    typetax: !ruby/object:TypeTax
      id: 2
      name: Normal
      tax: 10
- !ruby/object:Product
  id: 3
  name: Chocolate Bar
  producttype: !ruby/object:ProductType
    id: 3
    name: Food
    typetax: !ruby/object:TypeTax
      id: 3
      name: Exempt
      tax: 0
- !ruby/object:Product
  id: 4
  name: Imported Box of Chocolates
  producttype: !ruby/object:ProductType
    id: 4
    name: Imported
    typetax: !ruby/object:TypeTax
      id: 4
      name: Importted
      tax: 5
- !ruby/object:Product
  id: 5
  name: Imported Bottle of Perfume
  producttype: !ruby/object:ProductType
    id: 5
    name: Imported Good
    typetax: !ruby/object:TypeTax
      id: 5
      name: NormalImportted
      tax: 15
- !ruby/object:Product
  id: 6
  name: Bottle of Perfume
  producttype: !ruby/object:ProductType
    id: 6
    name: Normal Good
    typetax: !ruby/object:TypeTax
      id: 6
      name: Normal
      tax: 10
- !ruby/object:Product
  id: 7
  name: Packet of Headache Pills
  producttype: !ruby/object:ProductType
    id: 7
    name: Medical Product
    typetax: !ruby/object:TypeTax
      id: 7
      name: Exempt
      tax: 0
- !ruby/object:Product
  id: 8
  name: Box of Imported Chocolates
  producttype: !ruby/object:ProductType
    id: 8
    name: Imported
    typetax: !ruby/object:TypeTax
      id: 8
      name: Importted
      tax: 5
- !ruby/object:Product
  id: 9
  name: Imported Bottle of Perfume
  producttype: !ruby/object:ProductType
    id: 9
    name: Imported Good
    typetax: !ruby/object:TypeTax
      id: 9
      name: NormalImportted
      tax: 15
